# Generated by Django 4.2.9 on 2024-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand_All_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.FloatField(verbose_name='Год')),
                ('mid_salary', models.FloatField(verbose_name='Средняя зп')),
                ('age', models.FloatField(verbose_name='Кол-во вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='Demand_UX_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.FloatField(verbose_name='Год')),
                ('mid_salary', models.FloatField(verbose_name='Средняя зп')),
                ('age', models.FloatField(verbose_name='Кол-во вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='Geography_AreaCount_All_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64, verbose_name='Город')),
                ('mid_salary', models.FloatField(verbose_name='Доля вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='Geography_AreaCount_UX_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64, verbose_name='Город')),
                ('mid_salary', models.FloatField(verbose_name='Доля вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='Geography_MidSalary_All_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64, verbose_name='Город')),
                ('mid_salary', models.FloatField(verbose_name='Средняя зп')),
            ],
        ),
        migrations.CreateModel(
            name='Geography_MidSalary_UX_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64, verbose_name='Город')),
                ('mid_salary', models.FloatField(verbose_name='Средняя зп')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_All_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64, verbose_name='Город')),
                ('mid_salary', models.FloatField(verbose_name='Средняя зп')),
            ],
        ),
        migrations.CreateModel(
            name='Skills_UX_Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64, verbose_name='Город')),
                ('mid_salary', models.FloatField(verbose_name='Средняя зп')),
            ],
        ),
    ]
