# Generated by Django 4.2.9 on 2024-01-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand_all_vacancies',
            options={'verbose_name': 'Востребованность по всем Профессиям'},
        ),
        migrations.AlterModelOptions(
            name='demand_ux_vacancies',
            options={'verbose_name': 'Востребованность по UX'},
        ),
        migrations.AlterModelOptions(
            name='geography_areacount_all_vacancies',
            options={'verbose_name': 'География Доля Вакансий по всем Профессиям'},
        ),
        migrations.AlterModelOptions(
            name='geography_areacount_ux_vacancies',
            options={'verbose_name': 'География Доля Вакансий по UX'},
        ),
        migrations.AlterModelOptions(
            name='geography_midsalary_all_vacancies',
            options={'verbose_name': 'География Уровень Зарплат по всем Профессиям'},
        ),
        migrations.AlterModelOptions(
            name='geography_midsalary_ux_vacancies',
            options={'verbose_name': 'География Уровень Зарплат по UX'},
        ),
        migrations.AlterModelOptions(
            name='skills_all_vacancies',
            options={'verbose_name': 'Навыки для всех профессий'},
        ),
        migrations.AlterModelOptions(
            name='skills_ux_vacancies',
            options={'verbose_name': 'Навыки для UX'},
        ),
        migrations.RemoveField(
            model_name='demand_all_vacancies',
            name='age',
        ),
        migrations.RemoveField(
            model_name='demand_ux_vacancies',
            name='age',
        ),
        migrations.RemoveField(
            model_name='skills_all_vacancies',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='skills_all_vacancies',
            name='mid_salary',
        ),
        migrations.RemoveField(
            model_name='skills_ux_vacancies',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='skills_ux_vacancies',
            name='mid_salary',
        ),
        migrations.AddField(
            model_name='demand_all_vacancies',
            name='year_count',
            field=models.IntegerField(null=True, verbose_name='Кол-во вакансий'),
        ),
        migrations.AddField(
            model_name='demand_ux_vacancies',
            name='year_count',
            field=models.IntegerField(null=True, verbose_name='Кол-во вакансий'),
        ),
        migrations.AddField(
            model_name='skills_all_vacancies',
            name='published_at',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='skills_all_vacancies',
            name='top_skills',
            field=models.CharField(max_length=600, null=True, verbose_name='Топ Навыков'),
        ),
        migrations.AddField(
            model_name='skills_ux_vacancies',
            name='published_at',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='skills_ux_vacancies',
            name='top_skills',
            field=models.CharField(max_length=600, null=True, verbose_name='Топ Навыков'),
        ),
        migrations.AlterField(
            model_name='demand_all_vacancies',
            name='mid_salary',
            field=models.IntegerField(verbose_name='Средняя зп'),
        ),
        migrations.AlterField(
            model_name='demand_ux_vacancies',
            name='mid_salary',
            field=models.IntegerField(verbose_name='Средняя зп'),
        ),
        migrations.AlterField(
            model_name='geography_midsalary_all_vacancies',
            name='mid_salary',
            field=models.IntegerField(verbose_name='Средняя зп'),
        ),
        migrations.AlterField(
            model_name='geography_midsalary_ux_vacancies',
            name='mid_salary',
            field=models.IntegerField(verbose_name='Средняя зп'),
        ),
    ]
