# Generated by Django 4.2.9 on 2024-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0003_alter_demand_all_vacancies_year_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand_all_vacancies',
            name='published_at',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='demand_ux_vacancies',
            name='published_at',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
